[package]
name = "piro"
version = "2.0.0"
authors = ["Ben Busby <contact@benbusby.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
hyper = "0.13.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2.25", features = ["full"] }
