[package]
name = "raztot"
version = "2.0.0"
authors = ["Ben Busby <benbusby@protonmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
hyper = "0.13.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.8", features = ["full"] }
